package constants

var Animals = []string{
  "Lion",
  "Tiger",
  "Elephant",
  "Giraffe",
  "Zebra",
  "Monkey",
  "Kangaroo",
  "Panda",
  "Bear",
  "Wolf",
  "Fox",
  "Deer",
  "Rabbit",
  "Squirrel",
  "Hedgehog",
  "Owl",
  "Eagle",
  "Hawk",
  "Penguin",
  "Dolphin",
  "Whale",
  "Shark",
  "Octopus",
  "Jellyfish",
  "Crocodile",
  "Alligator",
  "Snake",
  "Lizard",
  "Turtle",
  "Frog",
  "Toad",
  "Spider",
  "Ant",
  "Bee",
  "Butterfly",
  "Moth",
  "Ladybug",
  "Snail",
  "Worm",
  "Fish",
  "Cat",
  "Dog",
  "Horse",
  "Cow",
  "Pig",
  "Sheep",
  "Goat",
  "Chicken",
  "Duck",
  "Goose",
  "Turkey",
  "Hamster",
  "Guinea Pig",
  "Ferret",
  "Chinchilla",
  "Parrot",
  "Canary",
  "Goldfish",
  "Seagull",
  "Pelican",
  "Flamingo",
  "Ostrich",
  "Rhinoceros",
  "Hippopotamus",
  "Cheetah",
  "Leopard",
  "Gorilla",
  "Chimpanzee",
  "Orangutan",
  "Baboon",
  "Coyote",
  "Badger",
  "Beaver",
  "Otter",
  "Seal",
  "Walrus",
  "Polar Bear",
  "Moose",
  "Bison",
  "Camel",
  "Llama",
  "Alpaca",
  "Donkey",
  "Mule",
  "Yak",
  "Gazelle",
  "Impala",
  "Wildebeest",
  "Kudu",
  "Eland",
  "Tapir",
  "Puma",
  "Jaguar",
  "Sloth",
  "Armadillo",
  "Anteater",
  "Platypus",
  "Echidna",
  "Koala",
  "Wombat",
  "Tasmanian Devil",
  "Meerkat",
  "Fennec Fox",
  "Pangolin",
  "Okapi",
  "Manatee",
  "Dugong",
  "Narwhal",
  "Beluga Whale",
  "Orca",
  "Blue Whale",
  "Humpback Whale",
  "Sperm Whale",
  "Great White Shark",
  "Hammerhead Shark",
  "Tiger Shark",
  "Manta Ray",
  "Stingray",
  "Electric Eel",
  "Piranha",
  "Clownfish",
  "Seahorse",
  "Starfish",
  "Sea Urchin",
  "Crab",
  "Lobster",
  "Shrimp",
  "Barnacle",
  "Oyster",
  "Mussel",
  "Clam",
  "Squid",
  "Cuttlefish",
  "Nautilus",
  "Gecko",
  "Chameleon",
  "Iguana",
  "Komodo Dragon",
  "Gila Monster",
  "Cobra",
  "Viper",
  "Python",
  "Boa Constrictor",
  "Rattlesnake",
  "King Cobra",
  "Black Mamba",
  "Green Anaconda",
  "Garter Snake",
  "Corn Snake",
  "Milk Snake",
  "Bullfrog",
  "Poison Dart Frog",
  "Tree Frog",
  "Salamander",
  "Newt",
  "Axolotl",
  "Tarantula",
  "Scorpion",
  "Centipede",
  "Millipede",
  "Cockroach",
  "Grasshopper",
  "Cricket",
  "Dragonfly",
  "Damselfly",
  "Mosquito",
  "Fly",
  "Wasp",
  "Hornet",
  "Termite",
  "Locust",
  "Praying Mantis",
  "Stick Insect",
  "Leaf Insect",
  "Beetle",
  "Weevil",
  "Glowworm",
  "Firefly",
  "Cicada",
  "Mayfly",
  "Stonefly",
  "Caddisfly",
  "Flea",
  "Louse",
  "Tick",
  "Mite",
  "Slug",
  "Earthworm",
  "Leech",
  "Coral",
  "Anemone",
  "Sponge",
  "Hydra",
  "Planarian",
  "Roundworm",
  "Tapeworm",
  "Fluke",
  "Rotifer",
  "Brachiopod",
  "Bryozoan",
  "Sea Cucumber",
  "Sea Lily",
  "Feather Star",
  "Sand Dollar",
  "Sea Star",
  "Brittle Star",
  "Sea Squirt",
  "Lancelet",
  "Hagfish",
  "Lamprey",
  "Chimaera",
  "Coelacanth",
  "Lungfish",
  "Sturgeon",
  "Paddlefish",
  "Gar",
  "Bowfin",
  "Eel",
  "Herring",
  "Sardine",
  "Anchovy",
  "Tuna",
  "Mackerel",
  "Cod",
  "Haddock",
  "Pollock",
  "Halibut",
  "Flounder",
  "Sole",
  "Plaice",
  "Tilapia",
  "Perch",
  "Bass",
  "Trout",
  "Salmon",
  "Pike",
  "Carp",
  "Catfish",
  "Guppy",
  "Molly",
  "Swordtail",
  "Betta",
  "Angelfish",
  "Discus",
  "Tetra",
  "Cichlid",
  "Loach",
  "Corydoras",
  "Pleco",
  "Oscar",
  "Pufferfish",
  "Lionfish",
  "Stonefish",
  "Moray Eel",
  "Barracuda",
  "Swordfish",
  "Marlin",
  "Sailfish",
  "Tarpon",
  "Bonefish",
  "Permit",
  "Snook",
  "Redfish",
  "Speckled Trout",
  "Striped Bass",
  "Walleye",
  "Crappie",
  "Bluegill",
  "Sunfish",
  "Rockfish",
  "Lingcod",
  "Cabezon",
  "Greenling",
  "Wolf Eel",
  "Ratfish",
  "Skate",
  "Ray",
  "Sawfish",
  "Ghost Shark",
  "Frilled Shark",
  "Goblin Shark",
  "Cookiecutter Shark",
  "Lanternshark",
  "Dogfish",
  "Angelshark",
  "Wobbegong",
  "Carpet Shark",
  "Zebra Shark",
  "Leopard Shark",
  "Nurse Shark",
  "Lemon Shark",
  "Bull Shark",
  "Blacktip Shark",
  "Whitetip Shark",
  "Reef Shark",
  "Thresher Shark",
  "Mako Shark",
  "Porbeagle",
  "Salmon Shark",
  "Basking Shark",
  "Megamouth Shark",
  "Whale Shark",
  "Giant Squid",
  "Colossal Squid",
  "Vampire Squid",
  "Blue-ringed Octopus",
  "Mimic Octopus",
  "Flapjack Octopus",
  "Dumbo Octopus",
  "Glass Octopus",
  "Blanket Octopus",
  "Paper Nautilus",
  "Sea Hare",
  "Nudibranch",
  "Sea Slug",
  "Abalone",
  "Conch",
  "Whelk",
  "Periwinkle",
  "Limpet",
  "Chiton",
  "Scallop",
  "Cockle",
  "Razor Clam",
  "Geoduck",
  "Shipworm",
  "Teredo",
  "Acorn Barnacle",
  "Goose Barnacle",
  "Horseshoe Crab",
  "King Crab",
  "Snow Crab",
  "Dungeness Crab",
  "Blue Crab",
  "Stone Crab",
  "Hermit Crab",
  "Fiddler Crab",
  "Ghost Crab",
  "Spider Crab",
  "Coconut Crab",
  "Pill Bug",
  "Woodlouse",
  "Amphipod",
  "Isopod",
  "Copepod",
  "Krill",
  "Brine Shrimp",
  "Daphnia",
  "Water Flea",
  "Fairy Shrimp",
  "Triops",
  "Tardigrade",
  "Rotifer",
  "Gastrotrich",
  "Kinorhynch",
  "Loriciferan",
  "Priapulid",
  "Nematode",
  "Horsehair Worm",
  "Velvet Worm",
  "Arrow Worm",
  "Comb Jelly",
  "Box Jellyfish",
  "Portuguese Man o' War",
  "Sea Wasp",
  "Moon Jellyfish",
  "Lion's Mane Jellyfish",
  "Sea Nettle",
  "By-the-wind Sailor",
  "Blue Button",
  "Velella",
  "Siphonophore",
  "Sea Pen",
  "Sea Fan",
  "Sea Whip",
  "Brain Coral",
  "Staghorn Coral",
  "Mushroom Coral",
  "Bubble Coral",
  "Star Coral",
  "Cup Coral",
  "Black Coral",
  "Red Coral",
  "Organ Pipe Coral",
  "Tube Worm",
  "Feather Duster Worm",
  "Christmas Tree Worm",
  "Bobbit Worm",
  "Lugworm",
  "Ragworm",
  "Sandworm",
  "Fireworm",
  "Peanut Worm",
  "Spoon Worm",
  "Acorn Worm",
  "Phoronid",
  "Lamp Shell",
  "Moss Animal",
  "Sea Mat",
  "Sea Lace",
  "Sea Moss",
  "Glass Sponge",
  "Barrel Sponge",
  "Tube Sponge",
  "Vase Sponge",
  "Finger Sponge",
  "Encrusting Sponge",
  "Demosponges",
  "Calcarea",
  "Hexactinellida",
  "Choanoflagellate",
  "Amoeba",
  "Paramecium",
  "Euglena",
  "Volvox",
  "Plasmodium",
  "Trypanosoma",
  "Giardia",
  "Leishmania",
  "Trichomonas",
  "Ciliate",
  "Flagellate",
  "Sporozoan",
  "Radiolarian",
  "Foraminiferan",
  "Diatom",
  "Dinoflagellate",
  "Coccolithophore",
  "Cyanobacteria",
  "Archaea",
  "Bacteria",
  "Virus",
  "Prion",
}