package constants

var Countries = []string{
    "United States",
    "Canada",
    "Mexico",
    "Brazil",
    "Argentina",
    "United Kingdom",
    "France",
    "Germany",
    "Italy",
    "Spain",
    "Portugal",
    "Netherlands",
    "Belgium",
    "Switzerland",
    "Austria",
    "Sweden",
    "Norway",
    "Denmark",
    "Finland",
    "Ireland",
    "Australia",
    "New Zealand",
    "Japan",
    "China",
    "India",
    "South Korea",
    "Indonesia",
    "Thailand",
    "Vietnam",
    "Philippines",
    "Malaysia",
    "Singapore",
    "Egypt",
    "South Africa",
    "Nigeria",
    "Kenya",
    "Morocco",
    "Algeria",
    "Saudi Arabia",
    "United Arab Emirates",
    "Turkey",
    "Russia",
    "Poland",
    "Czech Republic",
    "Hungary",
    "Greece",
    "Israel",
    "Colombia",
    "Chile",
    "Peru",
    "Venezuela",
    "Ecuador",
    "Bolivia",
    "Paraguay",
    "Uruguay",
    "Cuba",
    "Dominican Republic",
    "Jamaica",
    "Panama",
    "Costa Rica",
    "Guatemala",
    "Honduras",
    "El Salvador",
    "Nicaragua",
    "Afghanistan",
    "Pakistan",
    "Bangladesh",
    "Sri Lanka",
    "Nepal",
    "Myanmar",
    "Laos",
    "Cambodia",
    "Mongolia",
    "Kazakhstan",
    "Uzbekistan",
    "Ukraine",
    "Romania",
    "Bulgaria",
    "Serbia",
    "Croatia",
    "Bosnia and Herzegovina",
    "Slovenia",
    "Slovakia",
    "Lithuania",
    "Latvia",
    "Estonia",
    "Belarus",
    "Moldova",
    "Georgia",
    "Armenia",
    "Azerbaijan",
    "Iran",
    "Iraq",
    "Syria",
    "Lebanon",
    "Jordan",
    "Yemen",
    "Oman",
    "Qatar",
    "Kuwait",
    "Bahrain",
    "Ethiopia",
    "Tanzania",
    "Uganda",
    "Ghana",
    "Ivory Coast",
    "Cameroon",
    "Angola",
    "Mozambique",
    "Zambia",
    "Zimbabwe",
    "Madagascar",
    "Mauritius",
    "Fiji",
    "Papua New Guinea",
}